# Generated by Django 4.1.9 on 2024-03-13 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=1000)),
                ('mobile_no', models.CharField(blank=True, max_length=13, null=True)),
                ('is_user_staff', models.BooleanField()),
                ('password', models.CharField(blank=True, max_length=11, null=True)),
                ('billing_permission', models.BooleanField()),
                ('appointment_permission', models.BooleanField()),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Staff',
                'ordering': ['vendor_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slno', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(max_length=1000)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('services', models.CharField(max_length=100000)),
                ('service_by', models.CharField(max_length=40)),
                ('total_prise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_cgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('total_sgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('date', models.DateField()),
                ('month', models.CharField(blank=True, max_length=30, null=True)),
                ('week', models.CharField(blank=True, max_length=30, null=True)),
                ('year', models.CharField(blank=True, max_length=30, null=True)),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Invoice',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='VendorAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('services', models.CharField(blank=True, max_length=100000, null=True)),
                ('booking_date', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_time', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Appointment',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Vendor_Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=30)),
                ('service_price', models.CharField(max_length=30)),
                ('service_duration', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor_Service',
                'ordering': ['service'],
            },
        ),
        migrations.CreateModel(
            name='SwalookUserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salon_name', models.CharField(max_length=1000)),
                ('owner_name', models.CharField(max_length=1000)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vendor_id', models.CharField(max_length=6)),
                ('invoice_limit', models.IntegerField(default=0, null=True)),
                ('account_created_date', models.DateField(null=True)),
                ('user_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_staff', models.IntegerField(default=0)),
                ('s_gst_percent', models.CharField(max_length=30)),
                ('c_gst_percent', models.CharField(max_length=30)),
                ('current_billslno', models.CharField(max_length=50)),
                ('appointment_limit', models.IntegerField(default=0, null=True)),
                ('invoice_generated', models.IntegerField()),
                ('appointment_generated', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vendor_Profile',
                'ordering': ['salon_name'],
                'unique_together': {('salon_name', 'mobile_no')},
            },
        ),
    ]
