# Generated by Django 4.1.9 on 2024-03-14 20:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='book')),
            ],
        ),
    ]
