# Generated by Django 5.0.6 on 2024-05-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0004_delete_book_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='swalookuserprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='swalookuserprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
