# Generated by Django 5.0.6 on 2024-05-30 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0005_swalookuserprofile_pan_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=1000)),
                ('branch_name', models.CharField(max_length=1000)),
                ('password', models.CharField(blank=True, max_length=11, null=True)),
                ('admin_password', models.CharField(blank=True, max_length=11, null=True)),
                ('staff_url', models.CharField(max_length=1000)),
                ('admin_url', models.CharField(max_length=1000)),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Branch',
                'ordering': ['vendor_name'],
            },
        ),
    ]
