# Generated by Django 5.0.6 on 2024-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0006_salonbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='swalookuserprofile',
            name='enc_pwd',
            field=models.CharField(default='0', max_length=1000),
            preserve_default=False,
        ),
    ]
