# Generated by Django 5.0.6 on 2024-06-02 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0007_swalookuserprofile_enc_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_service',
            name='vendor_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch'),
        ),
        migrations.AddField(
            model_name='vendorappointment',
            name='vendor_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='vendor_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch'),
        ),
        migrations.AddField(
            model_name='vendorstaff',
            name='vendor_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch'),
        ),
    ]
