# Generated by Django 5.0.6 on 2024-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0008_vendor_service_vendor_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swalookuserprofile',
            name='branch_limit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
