# Generated by Django 5.0.6 on 2024-06-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0009_swalookuserprofile_branch_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='swalookuserprofile',
            name='branches_created',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
