# Generated by Django 5.0.6 on 2024-06-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0010_swalookuserprofile_branches_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swalookuserprofile',
            name='branch_limit',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
