# Generated by Django 5.0.6 on 2024-06-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0011_alter_swalookuserprofile_branch_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='vendor_branch_name',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
    ]
