# Generated by Django 5.0.6 on 2024-07-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0014_alter_businessanalysis_id_helpdesk'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorappointment',
            name='comment',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='comment',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
    ]
