# Generated by Django 5.0.6 on 2024-07-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0015_vendorappointment_comment_vendorinvoice_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorappointment',
            name='comment',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='comment',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
