# Generated by Django 5.0.6 on 2024-07-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0016_alter_vendorappointment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorappointment',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
