# Generated by Django 5.0.6 on 2024-07-21 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0017_vendorappointment_file_pdf_vendorinvoice_file_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPdf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('date', models.DateField()),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.vendorinvoice')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
            ],
            options={
                'verbose_name': 'Vendor Invoice Pdf',
                'ordering': ['date'],
            },
        ),
    ]
