# Generated by Django 5.0.6 on 2024-07-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0018_vendorpdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorpdf',
            old_name='file_pdf',
            new_name='file',
        ),
    ]
