# Generated by Django 5.0.6 on 2024-07-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0019_rename_file_pdf_vendorpdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='file_pdf',
        ),
        migrations.AddField(
            model_name='vendorpdf',
            name='customer_name',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorpdf',
            name='mobile_no',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorpdf',
            name='vendor_branch_name',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
    ]
