# Generated by Django 5.0.6 on 2024-07-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0020_remove_vendorinvoice_file_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpdf',
            name='email',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
