# Generated by Django 5.0.6 on 2024-07-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0021_vendorpdf_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpdf',
            name='invoice',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorpdf',
            name='mobile_no',
            field=models.CharField(max_length=1000000),
        ),
    ]
