# Generated by Django 5.0.6 on 2024-07-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0022_alter_vendorpdf_invoice_alter_vendorpdf_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpdf',
            name='invoice',
            field=models.CharField(max_length=100000000),
        ),
    ]
